### ISSUE TITLE
Doesn't work with pip

### ISSUE THREAD

**Issue by CrazyPython** [Miserlou/Zalgo#1]
I tried both `pip install zalgo` and `pip3 install zalgo`. Really nice project, by the way.

```
  Could not find a version that satisfies the requirement zalgo (from versions: )
No matching distribution found for zalgo
```

**Comment by Miserlou** [comment]
You're right! Crazy.

`zalgo` was squatted, so published to `zalgotext`. I have no idea if it works with P3.

**Comment by CrazyPython** [comment]
@Miserlou I think 2to3 could automatically convert your project.

**Comment by Miserlou** [comment]
ţ̘̭̫̝̹͆͆͆ͬ͆͆͆̐͆͆͐͆͆ͩ͆͆͟h͆̀͆į̳̰͕͈͆̄͆͆͆͆̿͆ͥ͆͆ͥ͆͆͆͆͢͠s̳͍͙̫̳͆͆ͤ͆͆͆͋͆͆͆̐͆͆ͅ ̸̴̡̜͆̍͆̾͆͆̐͆͆ͣ͆͆͆͒͆͆͜i̘͆̇͆̊͆ͪ͆͆̀͆҈̶͆̿͆̓͆̂͆͆s̷̩̪͖͆͆͆ͧ͆͆͆͆͜҈͆ ̢̛̜͆͆͆͒͆͆͆͌͆̚f̴̶̹͖̥̜͆͆͐͆͂͆̓͆͛͆͆͆͆ͣ͆̅͆͆͆͆̀͆̚i̵̢̞̲̙͎̥̯͆̐͆͆͆͆͆͆͆̉͆ͤ͆ͥ͆͆͆̏͆͆͆͆͆͆͜͠͡x̡͆̆͆̏͆͆ę͍̘̯̣͕͕͆̐͆͆͆͑͆ͬ͆̇͆̅͆̉͆͆͆̀͆͆̎͆̌͆͆͆͆̌͆͆͆͆̚ͅ҉͆d̺̮͆̃͆̓͆͆͆͆͒͆̃͆̓͆̏͆͟ ̫̮͈̥͙͆͆̒͆͆͆ͣ͆̈͆̄͆̇͆͆̐͆͆҈͆͗͆͛͆n̸͆͆̌͆ǫ̻͇̥͍͎̱͆͗͆͆͆ͥ͆͑͆͆͆͆̎͆͋͆͆́͆͒͆͐͆͌͆͆͆͆̚͠w̛̬͈͉̟͆͆͆͆͑͆ͨ͆̄͆͆
